### ISSUE TITLE
Docker build for 4.1 version

### ISSUE THREAD

**Issue by thyn** [aerospike-community/amc#24]
Thank you for the latest release. Is it possible to make docker build?
https://hub.docker.com/r/aerospike/amc

**Comment by realmgic** [comment]
Hi @thyn 

I'm still not sure how to update the Docker Hub, but I created a new `Dockerfile` for manual image building and usage.
I will probable expend it in the future if needed - but I guess it's good enough for now.

Feel free to try it and let me know if it helps.

Zohar

**Comment by thyn** [comment]
#25 fixes

**Comment by thyn** [comment]
now it's working, thank you
