### ISSUE TITLE
No nodes shown in Node section of dashboard with a six node cluster

### ISSUE THREAD

**Issue by mikeseggy** [aerospike-community/amc#31]
AMC 4.1.3.  I have a 6 node cluster.  The cluster summary panel shows six active nodes, however the "Nodes" panel does not  show any of them. I also have another enviroment with one node and it correctly shows this one node in the Nodes panel.
Cluster summary:
![image](https://user-images.githubusercontent.com/22229809/106295498-c1c5e180-620d-11eb-9f82-84fd3d9efff8.png)

Nothing in the nodes panel:
![image](https://user-images.githubusercontent.com/22229809/106295696-ffc30580-620d-11eb-960a-01002e127670.png)

**Comment by realmgic** [comment]
Ah, Thats weird.. Can you add more info? Are you using CE or EE cluster, what version, and maybe run a collectinfo and upload it so I can try and reproduce the issue?

**Comment by mikeseggy** [comment]
My servers are Community Edition  V 3.12.13 ( I know very downlevel ).  The one node environment that works has the same server level. 
Another thing that might be significant is that the server nodes in the 6 node cluster are each listening to port 3000 on two network interfaces.
![image](https://user-images.githubusercontent.com/22229809/106493299-313e0a00-6476-11eb-98f3-a2adc1ea1796.png)

  But the one node environment (which works), the server uses  only one interface.

**Comment by realmgic** [comment]
1. Are you running the AMC from one of the nodes of the cluster?
It might be that there is no connectivity from the AMC service to the nodes - so it can't pull the data off those node. Does the place you run AMC from can connect to the entire cluster as a client connection?

2. Did this used to work in an earlier version of AMC?

**Comment by mikeseggy** [comment]
No the AMC is running on a separate system but on the same subnet.   
We currently are using AMC version 4.0.19 ( community edition) and it shows the Nodes section of the dashboard correctly.  

I also installed AMC 4.0.27 and it also fails to show the Nodes section of the dashboard.

**Comment by realmgic** [comment]
I couldn't find a 3.12 binaries anywhere so I tested it with 3.13.0.11 (CE), and it appears that AMC 4.1.3 does support it. I used dockerized environment to test it.

Can you check the log file to see if there is anything useful there (`/var/log/amc/amc.log`) - and if not, can you try enabling debug logging (`/etc/amc/amc.conf`) to see what that gives us?

**Comment by mikeseggy** [comment]
Ok I will do that and get update.

**Comment by mikeseggy** [comment]
I enabled "debug" log level in my conf file , restarted the service and the only debug messages showing up in the log are these:

> time="2021-02-02T16:28:40Z" level=debug msg="Updating stats for cluster 04b1fa93-056c-4d14-a417-693f8252b6ac took: 29.033901ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB96CA10FC86102, objects: 271501, took: 12.373209ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB96EF490ECA902, objects: 257758, took: 12.764123ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB900DB40E14202, objects: 266477, took: 13.195474ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB9A4FA727D4802, objects: 260322, took: 13.698067ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB9FC815CBA0302, objects: 262857, took: 14.010159ms"
time="2021-02-02T16:28:45Z" level=debug msg="Updating Node: BB9A27DC6AECF02, objects: 266326, took: 14.17282ms"

FYI:  I noticed on that when I go into the "Select Nodes" under the gear icon on upper right of the dashboard it shows boxes for the six nodes, however the IP addresses are missing. I  am guessing a formatting issue with the two interfaces for each node. This is what I see when I hover over one of the boxes:
![image](https://user-images.githubusercontent.com/22229809/106631149-b4746400-6539-11eb-8a31-f29f9c58c898.png)

Also, the MultiCluster panel shows all six nodes as "green" dots:
![image](https://user-images.githubusercontent.com/22229809/106631978-82afcd00-653a-11eb-8087-b02532600c86.png)

See the Node IP.  I wonder if the two addresses are causing confusion.

**Comment by realmgic** [comment]
Looks like you might be right - can you check if your URL looks like? it should look something like this:
`http://amc-server:8081/#dashboard/localhost:3000/600/172.16.10.15:3000,172.16.10.18:3000,172.16.10.22:3000,172.16.10.4:3000 `
(the 172.16.10.x are my cluster nodes - 4, 15, 18 and 22).

It might be that the double address mess things up - I'm just not sure how to set up a test for that :)

**Comment by mikeseggy** [comment]
OK:
The URL has 12 IP addresses (after the seed node).  So it did pick up both interfaces on each node.
`http://my-amc-server:8081/#dashboard/XXX.XX.22.173:3000/30/XXX.XX.19.185:3000,XXX.XX.17.175:3000,XXX.XX.22.173:3000,XXX.XX.20.136:3000,XXX.XX.23.214:3000,XXX.XX.16.42:3000,XXX.XX.27.152:3000,XXX.XX.16.133:3000,XXX.XX.30.188:3000,XXX.XX.23.96:3000,XXX.XX.30.219:3000,XXX.XX.19.46:3000
`

**Comment by realmgic** [comment]
Okay, that's interesting - it seems that the AMC doesn't support multiple IP addresses for a single node. 
Let's confirm that: can you run this Go code snippet so we could see what is the host identifier returned from the server when having multiple IP addresses?

```
package main

import (
	"log"

	as "github.com/aerospike/aerospike-client-go"
	shared "github.com/aerospike/aerospike-client-go/examples/shared"
)

func main() {
	testgetNode(shared.Client)

	log.Println("Example finished successfully.")
}

/**
 * Write/Read map[string]boolean directly instead of relying on java serializer.
 */
func testgetNode(client *as.Client) {
	log.Printf("test getNode")

	Nodes := client.GetNodes()
	log.Println(Nodes)

	var host *as.Host

	for _, node := range Nodes {
		host = node.GetHost()
		log.Println("host:", host)

		infoMap, _ := node.RequestInfo(as.NewInfoPolicy(), "service")

		log.Println("service", infoMap)

	}

	log.Printf("Test getNode successful")
}
```

This uses our standard tester - so you should be able to run it like this:
`go run getNode.go -h 172.17.0.3`

If the `service` name we get from the info command is different from the `GetHost`, we will not found the node of the cluster.
If we can confirm this is the case, we can think about a solution for that.

**Comment by srinivas365** [comment]
Any update on this. I am also facing same issue

**Comment by realmgic** [comment]
@srinivas365 - since no one replied last time, there wasn't any progress on that. You can try running the above step and I can have a look at it.

Either way, please be advised that the AMC is no longer officially supported by Aerospike - it's all community driven.

**Comment by mikeseggy** [comment]
Hi I was pulled away from this as it wasn't a high priority for us. Thanks for the help anyway.
